name: py27
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch=0.3.1=py27_cuda8.0.61_cudnn7.1.2_3
  - torchvision=0.1.8=py27_0
  - pip:
    - pytreebank==0.2.4
    - tensorflow==1.3.0
    - tensorlayer==1.7.2
    - tensorpack==0.8.0
    - matplotlib
    - pathlib2
